### ISSUE TITLE
What ansible version do you use?

### ISSUE THREAD

**Issue by Oysed** [fitbeard/awx-without-k8s#132]
I try ansible core 2.12.10 - not work
TASK [awx : Start || Restart Postgres containers] 
Tuesday 12 November 2024  19:39:33 +0000 (0:00:00.553)       0:00:32.659 ******
fatal: [192.168.1.2]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"}

I try ansible core 2.14.17 - not work
Problem with community.docker.docker_compose
Need community.docker.docker_compose_v2

**Comment by fitbeard** [comment]
For dependencies this project is using poetry. You can find all dependencies inside pyproject.toml and poetry.lock files.

**Comment by Oysed** [comment]
Thanx playbook is working
