### ISSUE TITLE
Issue using custom EE environnement

### ISSUE THREAD

**Issue by mehdia4ever** [fitbeard/awx-without-k8s#50]
## Environment

OS: Red Hat Enterprise Linux release 8.6
Docker version 23.0.1, build a5ee5b1
AWX: v22

## Description

Am having i issue when i refresh the awx project using my custom EE.

I build the custom EE with this execution execution-environment.yml and a specific ansible version (2.12)

version: 1
dependencies:
galaxy: requirements.yml
python: requirements.txt

build_arg_defaults:
EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.12-latest'
ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c"
ansible_config: 'ansible.cfg'

additional_build_steps:
prepend:
...

## Logs : 

Traceback (most recent call last):
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 438, in _run_internal
lines = resultfile.readlines()
OSError: read() should have returned a bytes object, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 604, in run
res = receptor_job.run()
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 320, in run
res = self._run_internal(receptor_ctl)
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 447, in _run_internal
raise RuntimeError(detail)
RuntimeError: exit status 1

**Comment by fitbeard** [comment]
This situation was discussed earlier here https://github.com/fitbeard/awx-without-k8s/issues/45#issuecomment-1497488870

**Comment by mehdia4ever** [comment]
It not realy the same as https://github.com/fitbeard/awx-without-k8s/issues/45#issuecomment-1497488870, i used your custom EE to resolve it. 

Now, I used my own build EE , and i have issue with refreshing AWX project.

**Comment by fitbeard** [comment]
I you don’t understand how this whole thing works.  https://github.com/fitbeard/awx-without-k8s#modify-awx_ee_image_url-variable your own image or image from example is EE container on a host. It acts like a pod in k8s. Then inside AWX you can use any other image per execution environment or per inventory/project sync. EE on host is designed to run real(your) EE inside.
