### ISSUE TITLE
mitogen variable cannot be read when running playbook

### ISSUE THREAD

**Issue by mehdia4ever** [fitbeard/awx-without-k8s#52]
Hi,
# Description

I build my custom EE using your dockerfile, but when i integrate a mitogen strategy in my ansible.cfg i get error running a playbook.

**ansible.cfg**

[defaults]
strategy_plugins = /path_to_mitogen/ansible_mitogen/plugins/strategy
strategy = mitogen_linear

**ansible version:**
bash-4.4# ansible --version
ansible [core 2.12.5.post0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True

I also add ENV inside my EE container when a build it with your dockerfile
ANSIBLE_STRATEGY_PLUGINS=/path_to_mitogen/ansible_mitogen/plugins/strategy
ANSIBLE_STRATEGY=mitogen_linear

**Dockerfile:**
FROM quay.io/ansible/awx-ee:21.11.0

USER root
ENV http_proxy http://proxy:port
ENV https_proxy http://proxy:port
ENV HTTP_PROXY http://proxy:port
ENV HTTPS_PROXY http://proxy:port

RUN dnf -y update && \
    yum -y install podman crun procps && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.*

RUN useradd runner -u 1000 -g 0

ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/containers.conf /etc/containers/containers.conf
ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/podman-containers.conf /home/runner/.config/containers/containers.conf

RUN chmod 644 /etc/containers/containers.conf && sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' /etc/containers/storage.conf
RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; \
    touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; \
    touch /var/lib/shared/vfs-layers/layers.lock

RUN chown -R 1000:0 /home/runner/.config
COPY ansible.cfg /etc/ansible/ansible.cfg
RUN mkdir -p /usr/local/mitogen
ENV ANSIBLE_STRATEGY_PLUGINS=/path_to_mitogen/ansible_mitogen/plugins/strategy
ENV ANSIBLE_STRATEGY=mitogen_linear

RUN mkdir -p /etc/containers/registries.conf.d/ && echo "unqualified-search-registries = []" >> /etc/containers/registries.conf.d/force-fully-qualified-images.conf && \
    chmod 644 /etc/containers/registries.conf.d/force-fully-qualified-images.conf

RUN chmod 4755 /usr/bin/newgidmap /usr/bin/newuidmap

ENV _CONTAINERS_USERNS_CONFIGURED=""

USER 1000

# ERROR

ERROR! Invalid play strategy specified: mitogen_linear
The error appears to be in '/runner/project/test-ping.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

Any ideas about this ?

Thanks

**Comment by fitbeard** [comment]
Your workloads are executed inside a container (host ee) -> inside a container (inner podman container with execution environment):

`docker exec awx-ee podman images`

Do not touch outer container image, build EE container using official EE documentation, use these images for `execution environments`, search on the internet how to integrate mitogen in to EE with custom ansible version.

**Comment by mehdia4ever** [comment]
Thank's, ,i works, i add this variable in the Dockerfile and i build  a new custom ee image.

ENV ANSIBLE_STRATEGY=mitogen_linear
ENV ANSIBLE_STRATEGY_PLUGINS=/opt/mitogen/ansible_mitogen/plugins/strategy

RUN curl -L https://github.com/mitogen-hq/mitogen/archive/refs/tags/v0.3.3.tar.gz -o mitogen.tgz && \
    tar -xzf mitogen.tgz -C /opt && \
    ln -s /opt/mitogen-0.3.3 /opt/mitogen
